language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t kaitlinsickles/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kaitlinsickles/docker-react npm run test